// Generated by Wrangler on Tue May 14 2024 20:32:29 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	RAG_AGENT_KV: KVNamespace;
	RAG_AGENT_API_KEY: string;
	GITHUB_API_TOKEN: string;
	OPENAI_API_KEY: string;
	VECTORIZE_INDEX: VectorizeIndex;
	AI: unknown;
}
